### ISSUE TITLE
need to remodel base user

### ISSUE THREAD

**Issue by sxnityq** [experiment-0/experiment0#2]
BaseModel needs to be inherited from AbstractBaseUser.

Need to add additional attributes to BaseModel such as:
* username
* email
* phone
* role (foreign key to another class which will describe additional information)
* is_active
* is_staff
* is_superuser 
* objects (UserManager instance)
* USERNAME_FIELD = 'email'
* REQUIRED_FIELDS = ['username']

Need to create CustomUserManager

**Comment by Trionyx** [comment]
#3
